### ISSUE TITLE
JSON-LD example is broken

### ISSUE THREAD

**Issue by pietercolpaert** [smart-data-models/dataModel.GBFS#1]
When I try to parse https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld with a json-ld library it gives an error on the context.

Example ways to reproduce and test-cases that should work:

1. Command line

```bash
# npm install -g ldfetch
# ldfetch https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld

GET https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld
Failed to retrieve https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld: Error: Failed to load remote context https://smartdatamodels.org/context.jsonld: Unsupported JSON-LD media type application/json; charset=utf
```

2. Through a browser playground

https://rdf-play.rubensworks.net/#url=https%3A%2F%2Fsmart-data-models.github.io%2FdataModel.GBFS%2Fstation_status%2Fexamples%2Fexample-normalized.jsonld

 3. When using Comunica

https://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fsmart-data-models.github.io%2FdataModel.GBFS%2Fstation_status%2Fexamples%2Fexample-normalized.jsonld&query=SELECT%20*%20WHERE%20%7B%0A%20%20%0A%20%20%20%3Fs%20%3Fp%20%3Fo%20.%0A%20%20%0A%7D

**Comment by albertoabellagarcia** [comment]
I guess it could be a GitHub failure (not uncommon) now it is working properly without touching anything 
[https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld](https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld)

Regarding the [@context](https://smartdatamodels.org/context.jsonld) I see the error but the context remains accessible as well. I guess this should be solved by [https://rdf-play.rubensworks.net](https://rdf-play.rubensworks.net) or maybe the error is misleading us.

**Comment by pietercolpaert** [comment]
No, the headers on https://smartdatamodels.org/context.jsonld are incorrect. As far as I can see, you should:
 * [ ] [Enable Cross Origin Resource Sharing](https://enable-cors.org/)
 * [ ] Set the right content-type: `Content-Type: application/ld+json `

**Comment by albertoabellagarcia** [comment]
Could you show me an example in Github setting those headers?

**Comment by pietercolpaert** [comment]
> Could you show me an example in Github setting those headers?

This is not a github hosting issue, as your file hosted on github pages has all the right headers:

```bash
$ curl -I https://smart-data-models.github.io/dataModel.GBFS/station_status/examples/example-normalized.jsonld
HTTP/2 200 
server: GitHub.com
content-type: application/ld+json
access-control-allow-origin: *
etag: "61a97b57-81d"
```

The problem is with the context file that is referenced in this file (https://smartdatamodels.org/context.jsonld), where there is no such `content-type` or `access-control-allow-origin` header. A JSON-LD library is going to try to dereference the context in order to read this file, but is going to bump into something it is not allowed to fetch from another domain, and when it is able to fetch it, it is going to see that this is not indicated as an `application/ld+json` file and thus is not going to continue parsing the file.

```bash
$ curl -I https://smartdatamodels.org/context.jsonld
HTTP/1.1 200 OK
Date: Thu, 16 Dec 2021 18:33:17 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Thu, 16 Dec 2021 10:52:01 GMT
ETag: "1e573-5d341365cbb64"
Accept-Ranges: bytes
Content-Length: 124275
Content-Type: application/json; charset=utf-8
```

I can see from the headers you’re using Apache on that server. Adding a `.htaccess` file (or adding these 2 lines if it already exists) to the `/var/www` (or the real path of your public www dir) should do the trick:

```htaccess
Header set Access-Control-Allow-Origin *
AddType application/ld+json .jsonld
```

**Comment by albertoabellagarcia** [comment]
We will try to add headers to smartdamodels.org/context.jsonld  

This context is no longer updated as long as now every subject has its own context.jsonld in the root of every subject. 

Anyhow we will assess how to set the proper headers for this file.

**Comment by pietercolpaert** [comment]
Another solution would then be indeed to just not use `https://smartdatamodels.org/context.jsonld` in the examples and give each jsonld-file its own context!

**Comment by albertoabellagarcia** [comment]
We are reviewing all @context from all the data models' examples to include only the local @context  (and we will reorder the payloads so they all look the same way)
It will take a while (some hours)
